# fly.toml file generated for user-fastify-server on 2022-11-24T11:53:27+08:00

app = "user-fastify-server"
kill_signal = "SIGINT"
kill_timeout = 5
processes = []

[env]
  HOST = "0.0.0.0"
  PORT = 8080
  MONGODB_USERNAME = "mongo-admin"
  MONGODB_PASSWORD = "ohJ6iiIC1wLMMfzG"
  MONGODB_DATABASE = "sample_analytics"

[experimental]
  allowed_public_ports = []
  auto_rollback = true

[[services]]
  http_checks = []
  internal_port = 8080
  processes = ["app"]
  protocol = "tcp"
  script_checks = []
  [services.concurrency]
    hard_limit = 25
    soft_limit = 20
    type = "connections"

  [[services.ports]]
    force_https = true
    handlers = ["http"]
    port = 80

  [[services.ports]]
    handlers = ["tls", "http"]
    port = 443

  [[services.tcp_checks]]
    grace_period = "1s"
    interval = "15s"
    restart_limit = 0
    timeout = "2s"
